### ISSUE TITLE
Gauge-o-Matic Parameter Bar Glow Support

### ISSUE THREAD

**Issue by tmprnc** [katawajojo/AETHERIS-UI-AIO#4]
The plugin Gauge-o-Matic for Dalamud allows you to effectively do pretty much whatever you want with most UI elements tied to job gauges, and additionally supports some slight modifications to either one of parameter bars. The main intended purpose — at least the way I use it — is to display an additional indicator for when a buff that affects HP or MP is active; such as Bloodbath, a tank invuln, Lucid Dreaming, Thin Air, etc.

Here is what the glow effect looks like in vanilla:
https://github.com/user-attachments/assets/1e15876d-d67e-47c4-82fe-e4f2464da823

It does not display with AETHERIS, more than likely because the texture that the plugin uses to display the glow is either transparent or covered by another texture.
Is there a way to fix this without altering the visuals?

**Comment by katawajojo** [comment]
I also use Gauge-o-Matic and noticed this as well. I can take a look into figuring out why this is happening. I think the "fun" part is going to be hunting down what texture or whatnot that GoM is using for that glow.

**Comment by katawajojo** [comment]
Figured it out, this fix will be pushed with the next AETHERIS update.
![ffxiv_dx11_2024-07-25_08-28-23](https://github.com/user-attachments/assets/2df37527-f1b9-4256-a9f7-13826a3c8376)
