### ISSUE TITLE
Enhancement Request - Umbra colorset

### ISSUE THREAD

**Issue by Stormgail** [katawajojo/AETHERIS-UI-AIO#7]
I know it'd be a bunch of work so this is more of a wish than anything, but making a colorset to work with umbra https://github.com/una-xiv/umbra would be really cool so they could have a similar style!

**Comment by katawajojo** [comment]
Bonsaibnuuy actually made one back in July and posted it to the Umbra discord c:

https://discord.com/channels/1263935915517149298/1266577529540575333/1266577529540575333

**Comment by Stormgail** [comment]
Oh awesome, maybe just put a link to that on the GitHub for people like me
who look?
